nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar /home/ngtl/Atest/c_repos_part2.txt &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar /home/ngtl/Atest/c_repos_part3.txt &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/taosdata/TDengine.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/robertdavidgraham/masscan.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/SamyPesse/How-to-Make-a-Computer-Operating-System.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/nothings/stb.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/libuv/libuv.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/mpv-player/mpv.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/pbatard/rufus.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/emscripten-core/emscripten.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/stedolan/jq.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/pjreddie/darknet.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/coolsnowwolf/lede.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/cfenollosa/os-tutorial.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/ggreer/the_silver_searcher.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/tmux/tmux.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/curl/curl.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/bilibili/ijkplayer.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/wg/wrk.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/php/php-src.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/ventoy/Ventoy.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/obsproject/obs-studio.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/git/git.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/redis/redis.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/netdata/netdata.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/Genymobile/scrcpy.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/torvalds/linux.git &
nohup java -jar /home/ngtl/Atest/SAWMiner-1.0-SNAPSHOT.jar https://github.com/ApolloAuto/apollo &
